;; A "typical program": records, internal defines, closures, higher-order
;; procedures, strings and lists.
(define-record-type employee (make-employee name dept salary) employee?
  (name emp-name) (dept emp-dept) (salary emp-salary set-emp-salary!))
(define (make-staff n)
  (let loop ((i 0) (acc '()))
    (if (= i n) acc
        (loop (+ i 1)
              (cons (make-employee (string-append "e" (number->string i))
                                   (vector-ref #(sales eng ops) (modulo i 3))
                                   (+ 1000 (* 7 (modulo (* i 37) 101))))
                    acc)))))
(define (insert-sorted x lst less?)
  (cond ((null? lst) (list x))
        ((less? x (car lst)) (cons x lst))
        (else (cons (car lst) (insert-sorted x (cdr lst) less?)))))
(define (sort lst less?)
  (let loop ((rest lst) (acc '()))
    (if (null? rest) acc (loop (cdr rest) (insert-sorted (car rest) acc less?)))))
(define (summarise staff)
  (define (total-for dept)
    (let loop ((s staff) (sum 0))
      (cond ((null? s) sum)
            ((eq? (emp-dept (car s)) dept) (loop (cdr s) (+ sum (emp-salary (car s)))))
            (else (loop (cdr s) sum)))))
  (map (lambda (d) (cons d (total-for d))) '(sales eng ops)))
(define (raise-all! staff pct)
  (for-each (lambda (e) (set-emp-salary! e (+ (emp-salary e) (quotient (* pct (emp-salary e)) 100)))) staff))
(define (report staff)
  (let ((out (open-output-string)))
    (for-each (lambda (e) (write-string (emp-name e) out) (write-char #\space out)) staff)
    (string-length (get-output-string out))))
(define (run k)
  (let ((staff (make-staff 300)))
    (do ((i 0 (+ i 1))) ((= i k))
      (raise-all! staff 1)
      (summarise staff)
      (report (sort staff (lambda (a b) (< (emp-salary a) (emp-salary b))))))))
(run 6)
(display "done")
