;; data_tests.scm: records, bytevectors, and the list, symbol, character,
;; string and vector procedures of R7RS 6.1-6.10. Also re-run under
;; gc-threshold 1 by gc_stress_tests.scm.

(display "          === Testing records ===")
(newline)
(define-record-type <pare> (kons x y) pare? (x kar set-kar!) (y kdr))
(test-equal '(#t #f) (list (pare? (kons 1 2)) (pare? (cons 1 2))) "record predicate")
(test-equal '(1 2) (list (kar (kons 1 2)) (kdr (kons 1 2))) "record accessors")
(test-equal 3 (let ((k (kons 1 2))) (set-kar! k 3) (kar k)) "record modifier")
(test-equal "record accessor: expected a <pare> record, got (1 . 2)"
    (guard (e (#t (error-object-message e))) (kar (cons 1 2)))
    "an accessor checks the record type")
(define-record-type <other> (make-other x) other? (x other-x))
(test-equal #f (pare? (make-other 1)) "record types are distinct")
(test-equal '(3 5 #t #f)
    (let ()
      (define-record-type point (make-point x y) point? (x px) (y py set-py!))
      (define p (make-point 3 4))
      (set-py! p 5)
      (list (px p) (py p) (point? p) (point? 5)))
    "define-record-type in a body")
(define-record-type node (make-node val) node? (val node-val) (next node-next set-node-next!))
(test-equal 'tail
    (let ((n (make-node 1))) (set-node-next! n 'tail) (node-next n))
    "a field not set by the constructor can be set later")
(test-equal '(#t #f) (list (promise? (delay 1)) (vector? (delay 1))) "promises are records, not vectors")

(display "          === Testing bytevectors ===")
(newline)
(test-equal '(#t #f #f) (list (bytevector? #u8(1 2)) (bytevector? #(0 1)) (bytevector? '())) "bytevector?")
(test-equal 3 (bytevector-length (bytevector 0 1 2)) "bytevector and length")
(test-equal #u8(7 7 7) (make-bytevector 3 7) "make-bytevector with a fill")
(test-equal 255 (bytevector-u8-ref #u8(0 255) 1) "bytevector-u8-ref")
(test-equal #u8(1 9) (let ((b (bytevector 1 2))) (bytevector-u8-set! b 1 9) b) "bytevector-u8-set!")
(test-equal #u8(2 3) (bytevector-copy #u8(1 2 3 4) 1 3) "bytevector-copy with a range")
(test-equal #u8(1 1 2 4) (let ((b (bytevector 1 2 3 4))) (bytevector-copy! b 1 b 0 2) b) "overlapping bytevector-copy!")
(test-equal #u8(1 2 3) (bytevector-append #u8(1) #u8() #u8(2 3)) "bytevector-append")
(test-equal "λx" (utf8->string #u8(206 187 120)) "utf8->string")
(test-equal #u8(206 187) (string->utf8 "aλb" 1 2) "string->utf8 with a range")
(test-equal #t (equal? #u8(1 2) (bytevector 1 2)) "equal? compares bytevector contents")
(test-equal 'caught (guard (e (#t 'caught)) (bytevector 256)) "bytes are checked")

(display "          === Testing lists, symbols and booleans ===")
(newline)
(define circular (list 'a 'b))
(set-cdr! (cdr circular) circular)
(test-equal '(#t #t #f #f) (list (list? '(a b)) (list? '()) (list? '(a . b)) (list? circular)) "list?")
(test-equal "length: argument must be a proper list"
    (guard (e (#t (error-object-message e))) (length circular))
    "length of a circular list is an error, not a hang")
(test-equal '(3 3) (make-list 2 3) "make-list")
(test-equal '((1 2 3) "foo" (6 7 8 . 9)) (list (list-copy '(1 2 3)) (list-copy "foo") (list-copy '(6 7 8 . 9)))
    "list-copy")
(test-equal #f (let* ((a (list 1 2)) (b (list-copy a))) (eq? a b)) "list-copy makes new pairs")
(test-equal '(0 ("Sue" "Sue") "Anna")
    (let ((lst (list 0 '(2 2 2 2) "Anna"))) (list-set! lst 1 '("Sue" "Sue")) lst)
    "list-set!")
(test-equal '((c d) (101 102) (5 7) #f)
    (list (memq 'c '(a b c d)) (memv 101 '(100 101 102)) (assv 5 '((2 3) (5 7))) (assq 'x '((a 1))))
    "memq memv assv assq")
(test-equal '((2 3) (2 4)) (list (member 2.0 '(1 2 3) =) (assoc 2.0 '((1 1) (2 4) (3 9)) =))
    "member and assoc with a comparison procedure")
(test-equal '((a) c) (member '(a) '(b (a) c)) "member uses equal?")
(test-equal '(#t #f) (list (symbol=? 'a 'a 'a) (symbol=? 'a 'a 'b)) "symbol=?")
(test-equal '(#t #f) (list (boolean=? #t #t) (boolean=? #f #f #t)) "boolean=?")
(test-equal #t (eq? 'bitBlt (string->symbol "bitBlt")) "string->symbol interns")
(test-equal "K. Harper, M.D." (symbol->string (string->symbol "K. Harper, M.D.")) "symbol->string round trip")
(define cycle-2 (list 1 2 1 2))
(set-cdr! (cdddr cycle-2) cycle-2)
(define cycle-1 (list 1 2))
(set-cdr! (cdr cycle-1) cycle-1)
(test-equal #t (equal? cycle-1 cycle-2) "equal? terminates on cyclic lists")
(test-equal #f (equal? cycle-1 (list 1 2)) "a cyclic list is not equal to a finite one")
(test-equal #f (equal? 2 2.0) "equal? compares numbers with eqv?")
