;; data_tests.scm: records, bytevectors, and the list, symbol, character,
;; string and vector procedures of R7RS 6.1-6.10. Also re-run under
;; gc-threshold 1 by gc_stress_tests.scm.

(display "          === Testing records ===")
(newline)
(define-record-type <pare> (kons x y) pare? (x kar set-kar!) (y kdr))
(test-equal '(#t #f) (list (pare? (kons 1 2)) (pare? (cons 1 2))) "record predicate")
(test-equal '(1 2) (list (kar (kons 1 2)) (kdr (kons 1 2))) "record accessors")
(test-equal 3 (let ((k (kons 1 2))) (set-kar! k 3) (kar k)) "record modifier")
(test-equal "record accessor: expected a <pare> record, got (1 . 2)"
    (guard (e (#t (error-object-message e))) (kar (cons 1 2)))
    "an accessor checks the record type")
(define-record-type <other> (make-other x) other? (x other-x))
(test-equal #f (pare? (make-other 1)) "record types are distinct")
(test-equal '(3 5 #t #f)
    (let ()
      (define-record-type point (make-point x y) point? (x px) (y py set-py!))
      (define p (make-point 3 4))
      (set-py! p 5)
      (list (px p) (py p) (point? p) (point? 5)))
    "define-record-type in a body")
(define-record-type node (make-node val) node? (val node-val) (next node-next set-node-next!))
(test-equal 'tail
    (let ((n (make-node 1))) (set-node-next! n 'tail) (node-next n))
    "a field not set by the constructor can be set later")
(test-equal '(#t #f) (list (promise? (delay 1)) (vector? (delay 1))) "promises are records, not vectors")

(display "          === Testing bytevectors ===")
(newline)
(test-equal '(#t #f #f) (list (bytevector? #u8(1 2)) (bytevector? #(0 1)) (bytevector? '())) "bytevector?")
(test-equal 3 (bytevector-length (bytevector 0 1 2)) "bytevector and length")
(test-equal #u8(7 7 7) (make-bytevector 3 7) "make-bytevector with a fill")
(test-equal 255 (bytevector-u8-ref #u8(0 255) 1) "bytevector-u8-ref")
(test-equal #u8(1 9) (let ((b (bytevector 1 2))) (bytevector-u8-set! b 1 9) b) "bytevector-u8-set!")
(test-equal #u8(2 3) (bytevector-copy #u8(1 2 3 4) 1 3) "bytevector-copy with a range")
(test-equal #u8(1 1 2 4) (let ((b (bytevector 1 2 3 4))) (bytevector-copy! b 1 b 0 2) b) "overlapping bytevector-copy!")
(test-equal #u8(1 2 3) (bytevector-append #u8(1) #u8() #u8(2 3)) "bytevector-append")
(test-equal "λx" (utf8->string #u8(206 187 120)) "utf8->string")
(test-equal #u8(206 187) (string->utf8 "aλb" 1 2) "string->utf8 with a range")
(test-equal #t (equal? #u8(1 2) (bytevector 1 2)) "equal? compares bytevector contents")
(test-equal 'caught (guard (e (#t 'caught)) (bytevector 256)) "bytes are checked")

(display "          === Testing lists, symbols and booleans ===")
(newline)
(define circular (list 'a 'b))
(set-cdr! (cdr circular) circular)
(test-equal '(#t #t #f #f) (list (list? '(a b)) (list? '()) (list? '(a . b)) (list? circular)) "list?")
(test-equal "length: argument must be a proper list"
    (guard (e (#t (error-object-message e))) (length circular))
    "length of a circular list is an error, not a hang")
(test-equal '(3 3) (make-list 2 3) "make-list")
(test-equal '((1 2 3) "foo" (6 7 8 . 9)) (list (list-copy '(1 2 3)) (list-copy "foo") (list-copy '(6 7 8 . 9)))
    "list-copy")
(test-equal #f (let* ((a (list 1 2)) (b (list-copy a))) (eq? a b)) "list-copy makes new pairs")
(test-equal '(0 ("Sue" "Sue") "Anna")
    (let ((lst (list 0 '(2 2 2 2) "Anna"))) (list-set! lst 1 '("Sue" "Sue")) lst)
    "list-set!")
(test-equal '((c d) (101 102) (5 7) #f)
    (list (memq 'c '(a b c d)) (memv 101 '(100 101 102)) (assv 5 '((2 3) (5 7))) (assq 'x '((a 1))))
    "memq memv assv assq")
(test-equal '((2 3) (2 4)) (list (member 2.0 '(1 2 3) =) (assoc 2.0 '((1 1) (2 4) (3 9)) =))
    "member and assoc with a comparison procedure")
(test-equal '((a) c) (member '(a) '(b (a) c)) "member uses equal?")
(test-equal '(#t #f) (list (symbol=? 'a 'a 'a) (symbol=? 'a 'a 'b)) "symbol=?")
(test-equal '(#t #f) (list (boolean=? #t #t) (boolean=? #f #f #t)) "boolean=?")
(test-equal #t (eq? 'bitBlt (string->symbol "bitBlt")) "string->symbol interns")
(test-equal "K. Harper, M.D." (symbol->string (string->symbol "K. Harper, M.D.")) "symbol->string round trip")
(define cycle-2 (list 1 2 1 2))
(set-cdr! (cdddr cycle-2) cycle-2)
(define cycle-1 (list 1 2))
(set-cdr! (cdr cycle-1) cycle-1)
(test-equal #t (equal? cycle-1 cycle-2) "equal? terminates on cyclic lists")
(test-equal #f (equal? cycle-1 (list 1 2)) "a cyclic list is not equal to a finite one")
(test-equal #f (equal? 2 2.0) "equal? compares numbers with eqv?")

(display "          === Testing characters and strings ===")
(newline)
(test-equal '(#t #t #t #t #t)
    (list (char=? #\a #\a #\a) (char<? #\a #\b #\c) (char>? #\c #\b #\a) (char<=? #\a #\b #\b) (char>=? #\b #\b #\a))
    "character comparisons take any number of arguments")
(test-equal '(#t #t #f) (list (char-ci=? #\a #\A #\a) (char-ci<? #\a #\B #\c) (char-ci>? #\a #\A)) "char-ci comparisons")
(test-equal '(#t #t #t #t #t #f)
    (list (char-alphabetic? #\x39B) (char-upper-case? #\x39B) (char-lower-case? #\x3BB)
          (char-numeric? #\x0E50) (char-whitespace? #\x3000) (char-alphabetic? #\3))
    "Unicode character predicates")
(test-equal '(3 4 0 #f) (list (digit-value #\3) (digit-value #\x0664) (digit-value #\x0AE6) (digit-value #\.))
    "digit-value in several scripts")
(test-equal '(#\x39B #\x3BB #\x3BB #\xDF #\s)
    (list (char-upcase #\x3BB) (char-downcase #\x39B) (char-foldcase #\x39B) (char-upcase #\xDF) (char-foldcase #\x17F))
    "Unicode case mapping of characters")
(test-equal '(#t #t #t) (list (string=? "abc" "abc" "abc") (string<? "abc" "abcd" "acd") (string>=? "abcd" "abcd" "abc"))
    "string comparisons take any number of arguments")
(test-equal '(#t #t) (list (string-ci=? "ABC" "abc" "aBc") (string-ci<? "abc" "aBcD")) "string-ci comparisons")
(test-equal "mass" (string-foldcase "Maß") "string-foldcase of sharp s")
(test-equal '((#\b #\c) (#\b)) (list (string->list "abc" 1) (string->list "abc" 1 2)) "string->list with a range")
(test-equal '(#(#\B #\C) "2") (list (string->vector "ABC" 1) (vector->string #(#\1 #\2 #\3) 1 2))
    "string->vector and vector->string")
(test-equal "xx-xx" (let ((s (make-string 5 #\x))) (string-fill! s #\- 2 3) s) "string-fill! with a range")
(test-equal '("aabde" "abcab")
    (list (let ((s (string-copy "abcde"))) (string-copy! s 1 s 0 2) s)
          (let ((s (string-copy "abcde"))) (string-copy! s 3 s 0 2) s))
    "overlapping string-copy! in both directions")

;; Strings record whether they are all ASCII, which makes indexing O(1);
;; mutations that bring in other characters must turn that off.
(define mixed (string-copy "abcdef"))
(string-set! mixed 2 #\λ)
(test-equal '(#\λ #\d 6 "abλdef") (list (string-ref mixed 2) (string-ref mixed 3) (string-length mixed) mixed)
    "string-set! of a non-ASCII character into an ASCII string")
(string-set! mixed 2 #\c)
(test-equal '(#\c #\f 6 "abcdef") (list (string-ref mixed 2) (string-ref mixed 5) (string-length mixed) mixed)
    "string-set! back to ASCII")
(define filled (make-string 5 #\a))
(string-fill! filled #\𝄞 1 3)
(test-equal '("a𝄞𝄞aa" 5 #\a) (list filled (string-length filled) (string-ref filled 3))
    "string-fill! of a range with a non-ASCII character")
(define copied (make-string 4 #\-))
(string-copy! copied 1 "λx")
(test-equal '("-λx-" #\x) (list copied (string-ref copied 2)) "string-copy! of non-ASCII characters")
(test-equal '("bλd" "λ𝄞") (list (substring "abλde" 1 4) (string-copy "aλ𝄞" 1)) "substring and string-copy across non-ASCII")
(test-equal "string-ref: index out of bounds" (guard (e (#t (error-object-message e))) (string-ref "abc" 3))
    "string-ref past the end")
(test-equal "string-ref: expected a string, got 5" (guard (e (#t (error-object-message e))) (string-ref 5 0))
    "string-ref of a non-string")
(test-equal "string-copy!: the copied characters don't fit at that index"
    (guard (e (#t (error-object-message e))) (string-copy! (make-string 2 #\a) 1 "xy"))
    "string-copy! past the end")
(test-equal "aλc" (let ((s (string-copy "abc"))) (string-copy! s 1 "λ") s) "string-copy! with a multi-byte character")

(display "          === Testing vectors and mapping ===")
(newline)
(test-equal '(dah didah) (vector->list '#(dah dah didah) 1) "vector->list with a range")
(test-equal '(#(b) #(a b c d e f)) (list (vector-copy #(a b c) 1 2) (vector-append #(a b c) #(d e) #(f)))
    "vector-copy and vector-append")
(test-equal #(1 2 smash smash 5) (let ((vec (vector 1 2 3 4 5))) (vector-fill! vec 'smash 2 4) vec)
    "vector-fill! with a range")
(test-equal '(#(1 1 2 4 5) #(1 2 3 1 2))
    (list (let ((v (vector 1 2 3 4 5))) (vector-copy! v 1 v 0 2) v)
          (let ((v (vector 1 2 3 4 5))) (vector-copy! v 3 v 0 2) v))
    "overlapping vector-copy! in both directions")
(test-equal "StUdLyCaPs"
    (string-map (lambda (c k) (if (eqv? k #\u) (char-upcase c) (char-downcase c))) "studlycaps xxx" "ululululul")
    "string-map over two strings stops at the shorter")
(test-equal #(5 7 9) (vector-map + '#(1 2 3) '#(4 5 6 7)) "vector-map over two vectors")
(test-equal 9750
    (let ((ls1 (list 10 100 1000)) (ls2 (list 1 2 3 4 5 6)) (count 0))
      (set-cdr! (cddr ls1) ls1)
      (for-each (lambda (x y) (set! count (+ count (* x y)))) ls2 ls1)
      count)
    "for-each over several lists stops at the shortest, even with a circular one")
(test-equal '(101 100 99 98 97)
    (let ((v '())) (string-for-each (lambda (c) (set! v (cons (char->integer c) v))) "abcde") v)
    "string-for-each")
(test-equal '(0 1 4 9 16)
    (let ((v (make-list 5))) (vector-for-each (lambda (i) (list-set! v i (* i i))) '#(0 1 2 3 4)) v)
    "vector-for-each")
