;; port_tests.scm: ports and I/O (R7RS 6.13), and the printer through them.
;; Also re-run under gc-threshold 1 by gc_stress_tests.scm.

(display "          === Testing ports ===")
(newline)

(define (written obj)
  (let ((out (open-output-string))) (write obj out) (get-output-string out)))
(define (displayed obj)
  (let ((out (open-output-string))) (display obj out) (get-output-string out)))

;; --- string ports keep their state (they used to be copied)
(test-equal "abc \"x\"!\n"
    (let ((out (open-output-string)))
      (write 'abc out) (display " " out) (write "x" out) (write-char #\! out) (newline out)
      (get-output-string out))
    "output accumulates in a string port")
(test-equal '((a b) 42 "s" #t)
    (let ((in (open-input-string "(a b) 42 \"s\"")))
      (list (read in) (read in) (read in) (eof-object? (read in))))
    "successive reads from one string port")
(test-equal '("line one" #\l "ine two" "last" #t)
    (let ((in (open-input-string "line one\nline two\r\nlast")))
      (list (read-line in) (peek-char in) (begin (read-char in) (read-line in)) (read-line in)
            (eof-object? (read-line in))))
    "read-line handles \\n and \\r\\n")
(test-equal '("ab" "cdef" #t)
    (let ((in (open-input-string "abcdef")))
      (list (read-string 2 in) (read-string 10 in) (eof-object? (read-string 3 in))))
    "read-string")
(test-equal "el" (let ((out (open-output-string))) (write-string "hello" out 1 3) (get-output-string out))
    "write-string with a range")

;; --- predicates and closing
(test-equal '(#t #t #t #f #t)
    (let ((in (open-input-string "x")) (out (open-output-string)))
      (list (input-port? in) (output-port? out) (textual-port? out) (binary-port? out) (input-port-open? in)))
    "port predicates")
(test-equal '(#f #t "read-char: the port is closed")
    (let ((in (open-input-string "x")))
      (close-port in)
      (list (input-port-open? in) (input-port? in)
            (guard (e (#t (error-object-message e))) (read-char in))))
    "a closed port keeps its kind and refuses reads")

;; --- current ports are parameters
(test-equal "captured sym"
    (let ((out (open-output-string)))
      (parameterize ((current-output-port out)) (display "captured ") (write 'sym))
      (get-output-string out))
    "parameterize current-output-port")
(test-equal '(x 1)
    (parameterize ((current-input-port (open-input-string "x 1"))) (list (read) (read)))
    "parameterize current-input-port")
(test-equal #t (output-port? (current-error-port)) "current-error-port")
(test-equal 'rejected (guard (e (#t 'rejected)) (parameterize ((current-output-port 5)) 'no))
    "the current output port must be an output port")

;; --- files
(define port-test-file "tests/port-test.tmp")
(with-output-to-file port-test-file (lambda () (display "file text") (newline) (write '(1 "two"))))
(test-equal '("file text" (1 "two"))
    (with-input-from-file port-test-file (lambda () (list (read-line) (read))))
    "with-output-to-file and with-input-from-file")
(test-equal "file text"
    (call-with-input-file port-test-file read-line)
    "call-with-input-file")
(test-equal #t (file-exists? port-test-file) "file-exists?")
(delete-file port-test-file)
(test-equal #f (file-exists? port-test-file) "delete-file")
(test-equal #t (file-error? (guard (e (#t e)) (delete-file port-test-file))) "deleting a missing file is a file error")

;; --- binary ports
(test-equal '(1 1 #u8(2 3) #u8(4 5) #t)
    (let ((in (open-input-bytevector #u8(1 2 3 4 5))))
      (list (peek-u8 in) (read-u8 in) (read-bytevector 2 in) (read-bytevector 9 in) (eof-object? (read-u8 in))))
    "reading a bytevector port")
(test-equal '(2 #u8(1 6 7 4 5))
    (let ((bv (bytevector 1 2 3 4 5)))
      (list (read-bytevector! bv (open-input-bytevector #u8(6 7 8 9 10)) 1 3) bv))
    "read-bytevector!")
(test-equal #u8(1 3 4)
    (let ((out (open-output-bytevector)))
      (write-u8 1 out) (write-bytevector #u8(1 2 3 4 5) out 2 4) (get-output-bytevector out))
    "writing a bytevector port")
(let ((p (open-binary-output-file port-test-file)))
  (write-bytevector #u8(0 255 10) p)
  (close-port p))
(test-equal #u8(0 255 10) (call-with-port (open-binary-input-file port-test-file) (lambda (p) (read-bytevector 10 p)))
    "binary files round trip")
(delete-file port-test-file)
(test-equal "write-u8: not a binary output port"
    (guard (e (#t (error-object-message e))) (write-u8 1 (open-output-string)))
    "byte output to a textual port is an error")

;; --- the printer, now observable from Scheme
(test-equal "(\"a\\\"b\\\\c\\nd\" #\\space #\\x1)" (written (list "a\"b\\c\nd" #\space (integer->char 1)))
    "write escapes strings and names characters")
(test-equal "(a\"b c)" (displayed (list "a\"b" #\c)) "display shows strings and characters raw")
(test-equal "(|a b| |2| || nil)" (written (list (string->symbol "a b") (string->symbol "2") (string->symbol "") 'nil))
    "write puts bars on symbols that need them")
(test-equal "(2.0 1.0e+21 -0.0 +inf.0 1/3)" (written (list 2.0 1e21 -0.0 (/ 1.0 0) 1/3)) "write of numbers")
(define cyc (list 1 2))
(set-cdr! (cdr cyc) cyc)
(test-equal "#0=(1 2 . #0#)" (written cyc) "write labels a cycle")
(test-equal "#0=(1 2 . #0#)" (displayed cyc) "display labels a cycle too")
(define shared (list 1 2))
(test-equal "((1 2) (1 2))" (written (list shared shared)) "write doesn't label acyclic sharing")
(test-equal "(#0=(1 2) #0#)"
    (let ((out (open-output-string))) (write-shared (list shared shared) out) (get-output-string out))
    "write-shared labels shared structure")
(test-equal "((1 2) (1 2))"
    (let ((out (open-output-string))) (write-simple (list shared shared) out) (get-output-string out))
    "write-simple never labels")
(define self-vec (vector 1 2))
(vector-set! self-vec 1 self-vec)
(test-equal "#0=#(1 #0#)" (written self-vec) "write labels a cyclic vector")
(test-equal #t (let ((x (read (open-input-string (written cyc))))) (eq? x (cddr x)))
    "a written cycle reads back as a cycle")
;; --- procedures and other opaque objects
(define (printed-proc x) (+ x 1))
(test-equal "#<procedure printed-proc>" (written printed-proc) "a defined procedure prints with its name")
(test-equal "(#<procedure car> #<syntax if> #<procedure>)" (written (list car if (lambda () 1)))
    "built-ins, special forms and anonymous procedures")
(define (printed-adder n) (lambda (x) (+ x n)))
(define printed-add1 (printed-adder 1))
(define printed-alias printed-proc)
(test-equal "(#<procedure printed-add1> #<procedure printed-proc>)" (written (list printed-add1 printed-alias))
    "a procedure keeps the first name it is bound to")
(test-equal "#<procedure loop>" (let loop ((i 0)) (if (< i 2) (loop (+ i 1)) (written loop)))
    "named let names its procedure")
(test-equal "#<procedure inner>" (let () (define (inner) 1) (written inner)) "internal definitions name procedures")
(test-equal "(#<output-port string> #<input-port string>)"
    (written (list (open-output-string) (open-input-string "")))
    "ports print by kind")
(test-equal '(lambda (x) "doc" (define y 1) (+ x y))
    (let () (define (sourced x) "doc" (define y 1) (+ x y)) (procedure-source sourced))
    "procedure-source keeps docstrings and internal definitions")
(define-syntax printed-swap!
  (syntax-rules () ((_ a b) (let ((tmp a)) (set! a b) (set! b tmp)))))
(define-syntax printed-make
  (syntax-rules () ((_ name) (define (name p q) (printed-swap! p q) (let loop ((i 0)) (if (< i 1) (loop (+ i 1)) (list p q)))))))
(printed-make printed-made)
(test-equal '(lambda (p q) (printed-swap! p q) (let loop ((i 0)) (if (< i 1) (loop (+ i 1)) (list p q))))
    (procedure-source printed-made)
    "procedure-source shows a macro-made procedure's identifiers by name")
(test-equal '(case-lambda ((x) x) ((x . r) r)) (procedure-source (case-lambda ((x) x) ((x . r) r)))
    "procedure-source of case-lambda")
(test-equal #f (procedure-source car) "procedure-source of a built-in")
